"""
Django settings for fileapp project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.urls import reverse_lazy
import sentry_sdk
import dj_database_url
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.integrations.redis import RedisIntegration

#   env = environ.Env(
# set casting, default value
#     DEBUG=(bool, False)
# )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CHROMA_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
env_path = Path(".") / ".env"
load_dotenv(dotenv_path=env_path)

#   environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-+cp9p6kiylf#b1v@**szdgqs(9t-_koo2y&0u@e!1%0o!47cn')
#   CSRF_TRUSTED_ORIGINS = ['vercel.app']
CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', True)
CORS_ORIGIN_ALLOW_ALL = CORS_ALLOW_ALL_ORIGINS

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'authentication',
    'file',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'pwa',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fileapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fileapp.wsgi.application'
AUTH_USER_MODEL = 'authentication.CustomUser'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=500)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'file_db'),
            'USER': os.getenv('DB_USER', 'welzatm'),
            'PASSWORD': os.getenv('DB_PASS', 'Mayflower48'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

MISTRAL_UTIL_API_KEY = os.getenv('MISTRAL_UTIL_API_KEY')

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_STORAGE = "fileapp.custom_storage.AzureStaticStorage"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_FILE_STORAGE = 'fileapp.custom_storage.AzureMediaStorage'
AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME", "fsclfilemanager")
AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY", "9udZjS5p57ShBC5sypov07cdmDxaCtgPr1eeIoEAkhbcaPPRKg4w2YOAr/BpP5FNjQYLPcJrZ8ig+AStS5hPJg==")
AZURE_CONTAINER="media"
AZURE_STATIC_CONTAINER= "static"
AZURE_MEDIA_CONTAINER = "media"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', False)
EMAIL_PORT = int(os.getenv('EMAIL_PORT')) if os.getenv('EMAIL_PORT') else None
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
ELASTIC_API_KEY = os.getenv('ELASTIC_API_KEY')
BREVO_API_KEY = os.getenv('BREVO_API_KEY')

PWA_APP_NAME = 'FSCL FILE PORTAL'
PWA_APP_DESCRIPTION = "Secure file portal for Clients"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#f2f6f9'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_DEBUG_MODE = DEBUG
PWA_APP_ICONS = [
    {
        'src': 'https://fusionscl.com/wp-content/uploads/2020/04/cropped-Crop-FCSL-51-2.png',
        'sizes': '200x200'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': 'https://fusionscl.com/wp-content/uploads/2020/04/cropped-Crop-FCSL-51-2.png',
        'sizes': '200x200'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': 'https://fusionscl.com/wp-content/uploads/2020/04/cropped-Crop-FCSL-51-2.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'

CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0').strip()
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0').strip()

# CELERY_BROKER_URL = 'redis://default:ZrCgGHlkv8CK5zV1WmGREQNgdMjQH9MB@redis-14782.c56.east-us.azure.redns.redis
# -cloud' '.com:14782' CELERY_RESULT_BACKEND =
# 'redis://default:ZrCgGHlkv8CK5zV1WmGREQNgdMjQH9MB@redis-14782.c56.east-us.azure.redns.redis' '-cloud.com:14782'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

LOGIN_URL = reverse_lazy('login')

SENTRY_DSN = os.getenv('SENTRY_DSN')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            LoggingIntegration(),
            RedisIntegration(),
        ],
        traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0')),
        profiles_sample_rate=float(os.getenv('SENTRY_PROFILES_SAMPLE_RATE', '0')),
    )

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
# Backblaze B2 settings
#   DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', '')  # Leave this empty for Backblaze
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL', 's3.us-east-005.backblazeb2.com')  # Replace with your endpoint URL

# Optional: Set custom domain if you've set up a CNAME record
# AWS_S3_CUSTOM_DOMAIN = 'your_custom_domain.com'

# Additional settings
AWS_DEFAULT_ACL = None  # Use bucket defaults
AWS_S3_FILE_OVERWRITE = False  # Prevent overwriting existing files
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',  # Cache files for 24 hours
}

MISTRAL_API_KEY = os.getenv('MISTRAL_API_KEY')
MAILGUN_API_KEY = os.getenv('MAILGUN_API_KEY')
#   HF_TOKEN = os.getenv('HF_TOKEN')
#   HF_HUB_DISABLE_SYMLINKS_WARNING = os.getenv('HF_HUB_DISABLE_SYMLINKS_WARNING')
#   KMP_DUPLICATE_LIB_OK = os.getenv('KMP_DUPLICATE_LIB_OK')

MAX_REQUEST_BODY_SIZE = 15 * 1024 * 1024  # 15 MB

from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}
